//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppError
    {
        public int ID { get; set; }
        public string PageName { get; set; }
        public string FunctionName { get; set; }
        public string ErrorMessage { get; set; }
        public string LineNumber { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string StaffNumber { get; set; }
        public string ApplicationName { get; set; }
        public string VersionNumber { get; set; }
    }
}
