//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLog
    {
        public int Id { get; set; }
        public string ApplicationName { get; set; }
        public Nullable<System.DateTime> ActionDateTime { get; set; }
        public string ActionDesc { get; set; }
        public string Type { get; set; }
        public string JobGuid { get; set; }
    }
}
