//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalQuestionAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppraisalQuestionAnswer()
        {
            this.CrewAppraisalEvals = new HashSet<CrewAppraisalEval>();
        }
    
        public int Id { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string Answer { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public string guid { get; set; }
        public Nullable<int> Score { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewAppraisalEval> CrewAppraisalEvals { get; set; }
        public virtual AppraisalSectionQuestion AppraisalSectionQuestion { get; set; }
    }
}
