//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppraisalSection()
        {
            this.AppraisalSectionQuestions = new HashSet<AppraisalSectionQuestion>();
            this.CrewAppraisalEvals = new HashSet<CrewAppraisalEval>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AppraisalId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public string guid { get; set; }
        public Nullable<bool> HasComment { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<bool> Is_Csm { get; set; }
    
        public virtual Appraisal Appraisal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppraisalSectionQuestion> AppraisalSectionQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewAppraisalEval> CrewAppraisalEvals { get; set; }
    }
}
