//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appraisal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appraisal()
        {
            this.AppraisalSections = new HashSet<AppraisalSection>();
            this.CrewAppraisals = new HashSet<CrewAppraisal>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public string guid { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_CSM { get; set; }
        public Nullable<bool> Is_Crew { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppraisalSection> AppraisalSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewAppraisal> CrewAppraisals { get; set; }
    }
}
