//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockDeleteLog
    {
        public int Id { get; set; }
        public string BlockNo { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public string StaffNumber { get; set; }
        public Nullable<System.DateTime> BlockDate { get; set; }
        public string DeleteIntervelSetting { get; set; }
    }
}
