//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buses_Allocation
    {
        public int Id { get; set; }
        public Nullable<int> Bus_Id { get; set; }
        public Nullable<int> Group_Id { get; set; }
        public Nullable<System.DateTime> PickipDateTime { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual TransportGroup TransportGroup { get; set; }
    }
}
