//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CrewDetail()
        {
            this.Crew_Transports = new HashSet<Crew_Transports>();
            this.CrewTeamAssignments = new HashSet<CrewTeamAssignment>();
            this.PickupDetails = new HashSet<PickupDetail>();
            this.SharePointLogsTables = new HashSet<SharePointLogsTable>();
            this.OutOfBases = new HashSet<OutOfBase>();
            this.OCB_CrewPos = new HashSet<OCB_CrewPos>();
            this.SharePointLogs = new HashSet<SharePointLog>();
        }
    
        public string StaffNumber { get; set; }
        public string FullName { get; set; }
        public string Nation { get; set; }
        public string Category { get; set; }
        public string Lang1 { get; set; }
        public string Lang2 { get; set; }
        public string Lang3 { get; set; }
        public string Lang4 { get; set; }
        public string Sex { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crew_Transports> Crew_Transports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewTeamAssignment> CrewTeamAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickupDetail> PickupDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SharePointLogsTable> SharePointLogsTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutOfBase> OutOfBases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCB_CrewPos> OCB_CrewPos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SharePointLog> SharePointLogs { get; set; }
    }
}
