//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crew_Transports
    {
        public int Id { get; set; }
        public string StaffNumber { get; set; }
        public Nullable<int> Zone_Id { get; set; }
        public Nullable<int> Bus_Id { get; set; }
        public string Status { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual CrewDetail CrewDetail { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
