//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewEffectiveSeniorityPeriod
    {
        public int ID { get; set; }
        public Nullable<int> CESID { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> PeriodSeniority { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual CrewEffectiveSeniority CrewEffectiveSeniority { get; set; }
        public virtual Seniority_PeriodDetails Seniority_PeriodDetails { get; set; }
    }
}
