//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewTransportRequest
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> TransportType { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string FlightDetails { get; set; }
        public Nullable<System.DateTime> FlightDateTime { get; set; }
        public string StaffNumber { get; set; }
        public Nullable<bool> Is_deleted { get; set; }
        public string Status { get; set; }
    
        public virtual CrewTransportCategory CrewTransportCategory { get; set; }
        public virtual PilotCrewDetail PilotCrewDetail { get; set; }
    }
}
