//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewFlightFormAnswer
    {
        public int Id { get; set; }
        public int Crew_Flight_Form_Id { get; set; }
        public int Flight_Form_Section_Item_Id { get; set; }
        public string Answer { get; set; }
    
        public virtual CrewFlightForm CrewFlightForm { get; set; }
        public virtual FlightFormSectionItem FlightFormSectionItem { get; set; }
    }
}
