//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewWeightDetailList
    {
        public int Id { get; set; }
        public string Employee_Number { get; set; }
        public string Employee_Name { get; set; }
        public Nullable<System.DateTime> Date_From { get; set; }
        public Nullable<System.DateTime> Date_To { get; set; }
        public Nullable<System.DateTime> Date_Weight { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> Weight_Status_Id { get; set; }
        public Nullable<decimal> Gain_Loss { get; set; }
        public string Remarks { get; set; }
        public string Updated_By { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual Crew_Grooming_WeightStatus Crew_Grooming_WeightStatus { get; set; }
    }
}
