//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewAppraisal
    {
        public int Id { get; set; }
        public Nullable<int> CrewPosId { get; set; }
        public string AppraiserStaffNumber { get; set; }
        public Nullable<int> AppraisalId { get; set; }
        public Nullable<System.DateTime> SubmittedDateTime { get; set; }
        public Nullable<int> BlockId { get; set; }
        public string CrewComment { get; set; }
        public string AppraiserSignatureURL { get; set; }
        public string AppraiseeSignatureURL { get; set; }
    
        public virtual Appraisal Appraisal { get; set; }
        public virtual OCB_CrewPos OCB_CrewPos { get; set; }
    }
}
