//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewLeaveRequest
    {
        public int Id { get; set; }
        public string StaffNumber { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string LEAVE_REASON { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> SUBMITTED_TIME { get; set; }
        public string ADMIN_REASON { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Dt { get; set; }
    
        public virtual PilotCrewDetail PilotCrewDetail { get; set; }
    }
}
