//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crew_Grooming
    {
        public int Id { get; set; }
        public string StaffNumber { get; set; }
        public Nullable<int> Hair_Color_Cd { get; set; }
        public Nullable<int> Eye_Color_Cd { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Minimum_Weight { get; set; }
        public Nullable<decimal> Maximum_Weight { get; set; }
        public Nullable<int> Weight_Status_Id { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<System.DateTime> Weight_Entry_Date { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Updated_By { get; set; }
    
        public virtual Crew_Grooming_EyeColor Crew_Grooming_EyeColor { get; set; }
        public virtual Crew_Grooming_HairColor Crew_Grooming_HairColor { get; set; }
        public virtual PilotCrewDetail PilotCrewDetail { get; set; }
        public virtual Crew_Grooming_WeightStatus Crew_Grooming_WeightStatus { get; set; }
    }
}
