//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crew_WarningLetter
    {
        public int Id { get; set; }
        public string StaffNumber { get; set; }
        public Nullable<System.DateTime> WarnEntryDate { get; set; }
        public string WarnEntrySubject { get; set; }
        public string WarnEntryDesc { get; set; }
        public string WarnEntryType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Reported_By { get; set; }
        public string Updated_By { get; set; }
        public string AttachmentPath { get; set; }
        public string StaffName { get; set; }
    }
}
