//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewFlightForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CrewFlightForm()
        {
            this.CrewFlightFormAnswers = new HashSet<CrewFlightFormAnswer>();
            this.CrewFlightFormSectionComments = new HashSet<CrewFlightFormSectionComment>();
        }
    
        public int Id { get; set; }
        public int Flight_Id { get; set; }
        public int Flight_Form_Id { get; set; }
        public System.DateTime Submit_Date_and_Time { get; set; }
        public string StaffNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewFlightFormAnswer> CrewFlightFormAnswers { get; set; }
        public virtual FlightForm FlightForm { get; set; }
        public virtual OCB_Flights OCB_Flights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewFlightFormSectionComment> CrewFlightFormSectionComments { get; set; }
    }
}
