//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewTeamAssignment
    {
        public int Id { get; set; }
        public string StaffNumber { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Status { get; set; }
        public string Updated_By { get; set; }
    
        public virtual Appraisal_Team_Leads Appraisal_Team_Leads { get; set; }
        public virtual CrewDetail CrewDetail { get; set; }
    }
}
