//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewAppraisalEval
    {
        public int Id { get; set; }
        public Nullable<int> CrewAppraisalId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public string guid { get; set; }
        public Nullable<int> AnswerId { get; set; }
    
        public virtual AppraisalQuestionAnswer AppraisalQuestionAnswer { get; set; }
        public virtual AppraisalSection AppraisalSection { get; set; }
    }
}
