//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewTransportCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CrewTransportCategory()
        {
            this.CrewTransportRequests = new HashSet<CrewTransportRequest>();
        }
    
        public int Id { get; set; }
        public string Category { get; set; }
        public string Category_Desc { get; set; }
        public Nullable<bool> Is_deleted { get; set; }
        public Nullable<bool> Is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewTransportRequest> CrewTransportRequests { get; set; }
    }
}
