//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewGroomingAttribute
    {
        public int Id { get; set; }
        public string Employee_Number { get; set; }
        public string Employee_Name { get; set; }
        public string Hair_Color { get; set; }
        public string Eye_Color { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> Hair_Color_Cd { get; set; }
        public Nullable<int> Eye_Color_Cd { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
    }
}
