//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewEffectiveSeniority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CrewEffectiveSeniority()
        {
            this.CrewEffectiveSeniorityPeriods = new HashSet<CrewEffectiveSeniorityPeriod>();
        }
    
        public int ID { get; set; }
        public string CrewId { get; set; }
        public Nullable<int> GroupNo { get; set; }
        public Nullable<int> GroupSeniority { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Fleet { get; set; }
        public Nullable<int> NetSeniority { get; set; }
    
        public virtual PilotCrewDetail PilotCrewDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewEffectiveSeniorityPeriod> CrewEffectiveSeniorityPeriods { get; set; }
    }
}
