//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CSMEntities : DbContext
    {
        public CSMEntities()
            : base("name=CSMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AiportTimeZone> AiportTimeZones { get; set; }
        public virtual DbSet<AirportCode> AirportCodes { get; set; }
        public virtual DbSet<AppError> AppErrors { get; set; }
        public virtual DbSet<AppLog> AppLogs { get; set; }
        public virtual DbSet<Appraisal_Team_Leads> Appraisal_Team_Leads { get; set; }
        public virtual DbSet<AppraisalQuestionAnswer> AppraisalQuestionAnswers { get; set; }
        public virtual DbSet<Appraisal> Appraisals { get; set; }
        public virtual DbSet<AppraisalSectionQuestion> AppraisalSectionQuestions { get; set; }
        public virtual DbSet<AppraisalSection> AppraisalSections { get; set; }
        public virtual DbSet<BlockDeleteLog> BlockDeleteLogs { get; set; }
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<Buses_Allocation> Buses_Allocation { get; set; }
        public virtual DbSet<Buses_Drivers> Buses_Drivers { get; set; }
        public virtual DbSet<Crew_Appreciation> Crew_Appreciation { get; set; }
        public virtual DbSet<Crew_Commendation> Crew_Commendation { get; set; }
        public virtual DbSet<Crew_Grooming> Crew_Grooming { get; set; }
        public virtual DbSet<Crew_Grooming_EyeColor> Crew_Grooming_EyeColor { get; set; }
        public virtual DbSet<Crew_Grooming_HairColor> Crew_Grooming_HairColor { get; set; }
        public virtual DbSet<Crew_Grooming_WeightStatus> Crew_Grooming_WeightStatus { get; set; }
        public virtual DbSet<Crew_Transports> Crew_Transports { get; set; }
        public virtual DbSet<Crew_WarningLetter> Crew_WarningLetter { get; set; }
        public virtual DbSet<CrewAppraisalEval> CrewAppraisalEvals { get; set; }
        public virtual DbSet<CrewAppraisal> CrewAppraisals { get; set; }
        public virtual DbSet<CrewCategory> CrewCategories { get; set; }
        public virtual DbSet<CrewDetail> CrewDetails { get; set; }
        public virtual DbSet<CrewDocumentCategory> CrewDocumentCategories { get; set; }
        public virtual DbSet<CrewDocumentStatusHistory> CrewDocumentStatusHistories { get; set; }
        public virtual DbSet<CrewEffectiveSeniority> CrewEffectiveSeniorities { get; set; }
        public virtual DbSet<CrewEffectiveSeniorityPeriod> CrewEffectiveSeniorityPeriods { get; set; }
        public virtual DbSet<CrewFlightFormAnswer> CrewFlightFormAnswers { get; set; }
        public virtual DbSet<CrewFlightForm> CrewFlightForms { get; set; }
        public virtual DbSet<CrewFlightFormSectionComment> CrewFlightFormSectionComments { get; set; }
        public virtual DbSet<CrewGroomingAttribute> CrewGroomingAttributes { get; set; }
        public virtual DbSet<CrewGroomingRemark> CrewGroomingRemarks { get; set; }
        public virtual DbSet<CrewLeaveAnnouncement> CrewLeaveAnnouncements { get; set; }
        public virtual DbSet<CrewLeaveRequest> CrewLeaveRequests { get; set; }
        public virtual DbSet<CrewLeaveRosterPeriod> CrewLeaveRosterPeriods { get; set; }
        public virtual DbSet<CrewPhoto> CrewPhotos { get; set; }
        public virtual DbSet<CrewTeamAssignment> CrewTeamAssignments { get; set; }
        public virtual DbSet<CrewTransportCategory> CrewTransportCategories { get; set; }
        public virtual DbSet<CrewTransportRequest> CrewTransportRequests { get; set; }
        public virtual DbSet<CrewWeightDetailList> CrewWeightDetailLists { get; set; }
        public virtual DbSet<DepInfoSheet> DepInfoSheets { get; set; }
        public virtual DbSet<Doc_Category> Doc_Category { get; set; }
        public virtual DbSet<Doc_Crew_Log> Doc_Crew_Log { get; set; }
        public virtual DbSet<Doc_Files> Doc_Files { get; set; }
        public virtual DbSet<Doc_Versions> Doc_Versions { get; set; }
        public virtual DbSet<DocumentRejectReason> DocumentRejectReasons { get; set; }
        public virtual DbSet<DreversAccount> DreversAccounts { get; set; }
        public virtual DbSet<EmailSetting> EmailSettings { get; set; }
        public virtual DbSet<EvalSectionsComment> EvalSectionsComments { get; set; }
        public virtual DbSet<Exception_Log_Table> Exception_Log_Table { get; set; }
        public virtual DbSet<FAM_Form> FAM_Form { get; set; }
        public virtual DbSet<Fleet_Category> Fleet_Category { get; set; }
        public virtual DbSet<Fleet> Fleets { get; set; }
        public virtual DbSet<FlightForm> FlightForms { get; set; }
        public virtual DbSet<FlightFormSectionItem> FlightFormSectionItems { get; set; }
        public virtual DbSet<FlightFormSection> FlightFormSections { get; set; }
        public virtual DbSet<FlightMeal> FlightMeals { get; set; }
        public virtual DbSet<InactiveCrewList> InactiveCrewLists { get; set; }
        public virtual DbSet<InflightRestSheet> InflightRestSheets { get; set; }
        public virtual DbSet<Layover_Bids> Layover_Bids { get; set; }
        public virtual DbSet<Layover_Category> Layover_Category { get; set; }
        public virtual DbSet<Layover_Pairing> Layover_Pairing { get; set; }
        public virtual DbSet<Maximum_Bids> Maximum_Bids { get; set; }
        public virtual DbSet<MealsCount> MealsCounts { get; set; }
        public virtual DbSet<OCB_AC_Pos> OCB_AC_Pos { get; set; }
        public virtual DbSet<OCB_AllocationScreen> OCB_AllocationScreen { get; set; }
        public virtual DbSet<OCB_Blocks> OCB_Blocks { get; set; }
        public virtual DbSet<OCB_Comments> OCB_Comments { get; set; }
        public virtual DbSet<OCB_Crew_Pos_History> OCB_Crew_Pos_History { get; set; }
        public virtual DbSet<OCB_CrewPos> OCB_CrewPos { get; set; }
        public virtual DbSet<OCB_Flights> OCB_Flights { get; set; }
        public virtual DbSet<OCB_Notification> OCB_Notification { get; set; }
        public virtual DbSet<OCB_Upcoming_Crew> OCB_Upcoming_Crew { get; set; }
        public virtual DbSet<OtpFlightInfo> OtpFlightInfoes { get; set; }
        public virtual DbSet<OtpFlightStatu> OtpFlightStatus { get; set; }
        public virtual DbSet<otpGatesdep> otpGatesdeps { get; set; }
        public virtual DbSet<OtpPassengerDetail> OtpPassengerDetails { get; set; }
        public virtual DbSet<OutOfBase> OutOfBases { get; set; }
        public virtual DbSet<Pairing_Category> Pairing_Category { get; set; }
        public virtual DbSet<PickupDetail> PickupDetails { get; set; }
        public virtual DbSet<PilotCrewDetail> PilotCrewDetails { get; set; }
        public virtual DbSet<PilotCrewDocRejectReason> PilotCrewDocRejectReasons { get; set; }
        public virtual DbSet<PilotCrewDocument> PilotCrewDocuments { get; set; }
        public virtual DbSet<PilotCrewDocumentStatusHistory> PilotCrewDocumentStatusHistories { get; set; }
        public virtual DbSet<PilotDetail> PilotDetails { get; set; }
        public virtual DbSet<PotableWater> PotableWaters { get; set; }
        public virtual DbSet<PreBookedMeal> PreBookedMeals { get; set; }
        public virtual DbSet<PreFlight_Answers> PreFlight_Answers { get; set; }
        public virtual DbSet<PreFlight_Categories> PreFlight_Categories { get; set; }
        public virtual DbSet<PreFlight_Comments> PreFlight_Comments { get; set; }
        public virtual DbSet<PreFlight_CrewTest> PreFlight_CrewTest { get; set; }
        public virtual DbSet<PreFlight_FailedComments> PreFlight_FailedComments { get; set; }
        public virtual DbSet<PreFlight_Settings> PreFlight_Settings { get; set; }
        public virtual DbSet<PreFlight_TestExlude> PreFlight_TestExlude { get; set; }
        public virtual DbSet<PreFlight_TestLog> PreFlight_TestLog { get; set; }
        public virtual DbSet<PreFlight_TestQuestions> PreFlight_TestQuestions { get; set; }
        public virtual DbSet<Roster_Data> Roster_Data { get; set; }
        public virtual DbSet<Seniority_PeriodDetails> Seniority_PeriodDetails { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SharepointFilePrefix> SharepointFilePrefixes { get; set; }
        public virtual DbSet<SharePointLog> SharePointLogs { get; set; }
        public virtual DbSet<SharePointLogsTable> SharePointLogsTables { get; set; }
        public virtual DbSet<SpecialMeal> SpecialMeals { get; set; }
        public virtual DbSet<SSR> SSRs { get; set; }
        public virtual DbSet<SSR_Count> SSR_Count { get; set; }
        public virtual DbSet<StationManager> StationManagers { get; set; }
        public virtual DbSet<TransportGroup> TransportGroups { get; set; }
        public virtual DbSet<WeightMinMaxSetting> WeightMinMaxSettings { get; set; }
        public virtual DbSet<WeightVarianceSetting> WeightVarianceSettings { get; set; }
        public virtual DbSet<ZoneArea> ZoneAreas { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<vwRecency> vwRecencies { get; set; }
        public virtual DbSet<vwRecencySummary> vwRecencySummaries { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
