//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepInfoSheet
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public Nullable<int> Booked_Load_J { get; set; }
        public Nullable<int> Booked_Load_Y { get; set; }
        public Nullable<int> Final_Load_J { get; set; }
        public Nullable<int> Final_Load_Y { get; set; }
        public Nullable<int> Catered_Load_J { get; set; }
        public Nullable<int> Catered_Load_Y { get; set; }
        public Nullable<System.DateTime> F_D_Board_DateTime { get; set; }
        public string F_D_Board_Remarks { get; set; }
        public Nullable<System.DateTime> C_Crew_Boarded_DateTime { get; set; }
        public string C_Crew_Boarded_Remarks { get; set; }
        public Nullable<System.DateTime> Cleaners_On_DateTime { get; set; }
        public Nullable<System.DateTime> Cleaners_Off_DateTime { get; set; }
        public string Cleaners_Remarks { get; set; }
        public Nullable<System.DateTime> Caterer_On_DateTime { get; set; }
        public Nullable<System.DateTime> Caterer_Off_DateTime { get; set; }
        public string Caterer_Remarks { get; set; }
        public Nullable<System.DateTime> Boarding_DateTime { get; set; }
        public string Boarding_Remarks { get; set; }
        public Nullable<System.DateTime> First_Passenger_Boarded_DateTime { get; set; }
        public string First_Passenger_Boarded_Remarks { get; set; }
        public Nullable<System.DateTime> Last_Passenger_Boarded_DateTime { get; set; }
        public string Last_Passenger_Boarded_Remarks { get; set; }
        public Nullable<System.DateTime> Doors_Closed_DateTime { get; set; }
        public string Doors_Closed_Remarks { get; set; }
        public Nullable<bool> Landing_Cards_Provided { get; set; }
        public string Landing_Cards_Provided_Remarks { get; set; }
        public Nullable<bool> Ships_Papers_On_Board { get; set; }
        public string Ships_Papers_On_Board_Remarks { get; set; }
        public Nullable<bool> VIP_CIP { get; set; }
        public string VIP_CIP_Remarks { get; set; }
        public Nullable<bool> Cabin_Baggage_Labeled { get; set; }
        public string Cabin_Baggage_Labeled_Remarks { get; set; }
        public Nullable<bool> Cabin_Baggage_Compliant { get; set; }
        public string Cabin_Baggage_Compliant_Remarks { get; set; }
        public Nullable<bool> Special_Assistance { get; set; }
        public string Special_Assistance_Remarks { get; set; }
        public Nullable<bool> GEN_DEC { get; set; }
        public string GEN_DEC_Remarks { get; set; }
        public Nullable<bool> PIL_Provided { get; set; }
        public string PIL_Provided_Remarks { get; set; }
        public Nullable<int> WCHC { get; set; }
        public Nullable<int> WCHS { get; set; }
        public Nullable<int> WCHR { get; set; }
        public Nullable<int> MAAS { get; set; }
        public Nullable<int> BLND { get; set; }
        public Nullable<int> DEAF { get; set; }
        public Nullable<int> STCR { get; set; }
        public Nullable<int> INAD { get; set; }
        public Nullable<int> DEPU { get; set; }
        public Nullable<int> DEPA { get; set; }
        public Nullable<int> MEDA { get; set; }
        public Nullable<int> UMNR { get; set; }
        public Nullable<int> OTHER { get; set; }
        public string AdditionalComments { get; set; }
        public string Ground_staffnum { get; set; }
        public string Ground_staffname { get; set; }
        public string Ground_staffcomments { get; set; }
        public string Csm_Sign { get; set; }
        public string Ground_staffsign { get; set; }
        public string GsimageUrl { get; set; }
    
        public virtual OCB_Flights OCB_Flights { get; set; }
    }
}
