//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_Versions
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> RevFlightCrew { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    }
}
