# Use the official ASP.NET 4.8 Windows Server Core image as the base
#FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019

# Set the working directory to the default IIS web root
WORKDIR /inetpub/wwwroot

# Remove default IIS files
RUN powershell -Command "Remove-Item -Recurse -Force *"

# Copy the published output from your local machine to the container
# (First, publish your app from Visual Studio to a 'publish' folder)
COPY . .


ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]

# Expose port 80 for web traffic
EXPOSE 80