//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSetting
    {
        public int Id { get; set; }
        public string SMTPServer { get; set; }
        public string SMTPPort { get; set; }
        public string EmailUsername { get; set; }
        public string EmailFromPass { get; set; }
        public string EmailFrom { get; set; }
        public string Type { get; set; }
    }
}
