//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAM_Form
    {
        public int Id { get; set; }
        public int Flight_Id { get; set; }
        public int Crew_Pos_Id { get; set; }
        public string Staff_Number { get; set; }
        public string Rating { get; set; }
        public string Legal_Doc_Validity { get; set; }
        public Nullable<bool> pre_Flight_Check { get; set; }
        public Nullable<bool> pre_Passenger_Boarding_Check { get; set; }
        public Nullable<bool> passenger_Boarding_Check { get; set; }
        public Nullable<bool> exit_Seats_Briefing_Check { get; set; }
        public Nullable<bool> pre_Taxi { get; set; }
        public Nullable<bool> door_Arming { get; set; }
        public Nullable<bool> pre_Take_Off { get; set; }
        public Nullable<bool> lavatory_Cruise { get; set; }
        public Nullable<bool> cruise { get; set; }
        public Nullable<bool> desent { get; set; }
        public Nullable<bool> after_Landing { get; set; }
        public Nullable<bool> door_Disarming { get; set; }
        public Nullable<bool> door_Warning { get; set; }
        public Nullable<bool> door_Opening { get; set; }
        public Nullable<bool> terminating_Flights { get; set; }
        public Nullable<bool> departure_From_AC { get; set; }
        public string cSM_Comments { get; set; }
        public string sNY_Comments { get; set; }
    
        public virtual OCB_CrewPos OCB_CrewPos { get; set; }
        public virtual OCB_Flights OCB_Flights { get; set; }
    }
}
