//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightFormSectionItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightFormSectionItem()
        {
            this.CrewFlightFormAnswers = new HashSet<CrewFlightFormAnswer>();
        }
    
        public int Id { get; set; }
        public int Flight_Form_Section_Id { get; set; }
        public string ItemTitle { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewFlightFormAnswer> CrewFlightFormAnswers { get; set; }
        public virtual FlightFormSection FlightFormSection { get; set; }
    }
}
