//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightFormSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightFormSection()
        {
            this.CrewFlightFormSectionComments = new HashSet<CrewFlightFormSectionComment>();
            this.FlightFormSectionItems = new HashSet<FlightFormSectionItem>();
        }
    
        public int Id { get; set; }
        public int Flight_Form_Id { get; set; }
        public string SectionTitle { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewFlightFormSectionComment> CrewFlightFormSectionComments { get; set; }
        public virtual FlightForm FlightForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightFormSectionItem> FlightFormSectionItems { get; set; }
    }
}
