//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class InflightRestSheet
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public string RestingStaff { get; set; }
        public string TakingOverStaff { get; set; }
        public string Location { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string TotalTime { get; set; }
    }
}
