//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Layover_Bids
    {
        public int ID { get; set; }
        public Nullable<int> CAT_ID { get; set; }
        public Nullable<int> STN_ID { get; set; }
        public string FC_BOING_BIDLIMIT { get; set; }
        public string FC_AIRBUS_BIDLIMIT { get; set; }
        public string CM_BIDLIMIT { get; set; }
        public string CS_BIDLIMIT { get; set; }
        public string FG_FA_BIDLIMIT { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual AirportCode AirportCode { get; set; }
        public virtual Layover_Category Layover_Category { get; set; }
    }
}
