//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Layover_Pairing
    {
        public int ID { get; set; }
        public Nullable<int> Pair_Cat_ID { get; set; }
        public Nullable<int> Fleet_Id { get; set; }
        public string Pairing { get; set; }
        public Nullable<System.DateTime> Operation_Date { get; set; }
        public Nullable<System.DateTime> Next_Operation { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Fleet_Category Fleet_Category { get; set; }
        public virtual Pairing_Category Pairing_Category { get; set; }
    }
}
