//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maximum_Bids
    {
        public int ID { get; set; }
        public string BID_TYPE { get; set; }
        public string FC_BOING_MAX { get; set; }
        public string FC_AIRBUS_MAX { get; set; }
        public string CM_MAX { get; set; }
        public string CS_MAX { get; set; }
        public string FG_FA_MAX { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
