//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCB_CrewPos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OCB_CrewPos()
        {
            this.CrewAppraisals = new HashSet<CrewAppraisal>();
            this.FAM_Form = new HashSet<FAM_Form>();
            this.OCB_Comments = new HashSet<OCB_Comments>();
            this.OCB_Crew_Pos_History = new HashSet<OCB_Crew_Pos_History>();
            this.PreFlight_CrewTest = new HashSet<PreFlight_CrewTest>();
            this.PreFlight_TestExlude = new HashSet<PreFlight_TestExlude>();
            this.PreFlight_TestExlude1 = new HashSet<PreFlight_TestExlude>();
        }
    
        public int Id { get; set; }
        public string StaffNumber { get; set; }
        public string Category { get; set; }
        public string Nurse { get; set; }
        public Nullable<int> PosId { get; set; }
        public Nullable<bool> ManualAdd { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public string guid { get; set; }
        public Nullable<int> BlockId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewAppraisal> CrewAppraisals { get; set; }
        public virtual CrewDetail CrewDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAM_Form> FAM_Form { get; set; }
        public virtual OCB_AC_Pos OCB_AC_Pos { get; set; }
        public virtual OCB_Blocks OCB_Blocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCB_Comments> OCB_Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCB_Crew_Pos_History> OCB_Crew_Pos_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFlight_CrewTest> PreFlight_CrewTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFlight_TestExlude> PreFlight_TestExlude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFlight_TestExlude> PreFlight_TestExlude1 { get; set; }
    }
}
