//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCB_AC_Pos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OCB_AC_Pos()
        {
            this.OCB_Crew_Pos_History = new HashSet<OCB_Crew_Pos_History>();
            this.OCB_CrewPos = new HashSet<OCB_CrewPos>();
        }
    
        public int Id { get; set; }
        public string EQP { get; set; }
        public string PosCode { get; set; }
        public string PosDisc { get; set; }
        public string Door { get; set; }
        public string Family { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCB_Crew_Pos_History> OCB_Crew_Pos_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCB_CrewPos> OCB_CrewPos { get; set; }
    }
}
