//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCB_Flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OCB_Flights()
        {
            this.CrewFlightForms = new HashSet<CrewFlightForm>();
            this.DepInfoSheets = new HashSet<DepInfoSheet>();
            this.FAM_Form = new HashSet<FAM_Form>();
            this.FlightMeals = new HashSet<FlightMeal>();
            this.MealsCounts = new HashSet<MealsCount>();
            this.OCB_AllocationScreen = new HashSet<OCB_AllocationScreen>();
            this.OCB_Notification = new HashSet<OCB_Notification>();
            this.PotableWaters = new HashSet<PotableWater>();
            this.PreBookedMeals = new HashSet<PreBookedMeal>();
            this.PreFlight_CrewTest = new HashSet<PreFlight_CrewTest>();
            this.PreFlight_TestExlude = new HashSet<PreFlight_TestExlude>();
            this.SpecialMeals = new HashSet<SpecialMeal>();
            this.SSR_Count = new HashSet<SSR_Count>();
            this.SSRs = new HashSet<SSR>();
        }
    
        public int Id { get; set; }
        public string Flt_No { get; set; }
        public Nullable<System.DateTime> Flight_Date { get; set; }
        public string Orig { get; set; }
        public string Dest { get; set; }
        public string ReqLimit { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public string guid { get; set; }
        public Nullable<int> BlockId { get; set; }
        public string EQP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewFlightForm> CrewFlightForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepInfoSheet> DepInfoSheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAM_Form> FAM_Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightMeal> FlightMeals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealsCount> MealsCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCB_AllocationScreen> OCB_AllocationScreen { get; set; }
        public virtual OCB_Blocks OCB_Blocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCB_Notification> OCB_Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PotableWater> PotableWaters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreBookedMeal> PreBookedMeals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFlight_CrewTest> PreFlight_CrewTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFlight_TestExlude> PreFlight_TestExlude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialMeal> SpecialMeals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSR_Count> SSR_Count { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSR> SSRs { get; set; }
    }
}
