//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCB_Crew_Pos_History
    {
        public int Id { get; set; }
        public int CrewPosId { get; set; }
        public int PosId { get; set; }
    
        public virtual OCB_AC_Pos OCB_AC_Pos { get; set; }
        public virtual OCB_CrewPos OCB_CrewPos { get; set; }
    }
}
