//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCB_AllocationScreen
    {
        public int Id { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string RoomNumber { get; set; }
        public string Status { get; set; }
        public string Duty { get; set; }
    
        public virtual OCB_Flights OCB_Flights { get; set; }
    }
}
