//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCB_Blocks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OCB_Blocks()
        {
            this.OCB_CrewPos = new HashSet<OCB_CrewPos>();
            this.OCB_Flights = new HashSet<OCB_Flights>();
        }
    
        public int Id { get; set; }
        public string Block_No { get; set; }
        public Nullable<int> Days_No { get; set; }
        public Nullable<System.DateTime> Block_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> End_Time { get; set; }
        public string Eqp { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public string guid { get; set; }
        public Nullable<bool> Delay { get; set; }
        public Nullable<bool> ManualEdit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCB_CrewPos> OCB_CrewPos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCB_Flights> OCB_Flights { get; set; }
    }
}
