//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCB_Upcoming_Crew
    {
        public int Id { get; set; }
        public Nullable<int> fltNo { get; set; }
        public Nullable<System.DateTime> fltDate { get; set; }
        public string aircraftType { get; set; }
        public string baseStn { get; set; }
        public string BlockName { get; set; }
        public string StaffId { get; set; }
        public string Staff_FirstName { get; set; }
        public string Staff_LastName { get; set; }
        public string Staff_FullName { get; set; }
        public string Staff_ShortName { get; set; }
        public string Staff_Pos { get; set; }
        public string Staff_Qual_Cat { get; set; }
        public string Staff_Request { get; set; }
        public string Pax { get; set; }
        public string Staff_Notified { get; set; }
        public string Flt_Orgin { get; set; }
        public string Flt_Dest { get; set; }
        public string Rec_Unique_Id { get; set; }
    }
}
