//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtpFlightStatu
    {
        public int Id { get; set; }
        public string FltSeqNr { get; set; }
        public System.DateTime FltDt { get; set; }
        public string FltNr { get; set; }
        public int LegSeqNr { get; set; }
        public string OpSuffix { get; set; }
        public System.DateTime SchDepDt { get; set; }
        public System.DateTime PubSchDepDt { get; set; }
        public System.DateTime SchArvDt { get; set; }
        public System.DateTime PubSchArvDt { get; set; }
        public Nullable<System.DateTime> ActualOffblocks { get; set; }
        public Nullable<System.DateTime> ActualOnblocks { get; set; }
        public Nullable<System.DateTime> ActualAirborne { get; set; }
        public Nullable<System.DateTime> ActualLanding { get; set; }
        public Nullable<System.DateTime> LatestDepDt { get; set; }
        public Nullable<System.DateTime> LatestArvDt { get; set; }
        public string SchDepArpCd { get; set; }
        public string SchArvArpCd { get; set; }
        public string LatestDepArpCd { get; set; }
        public string LatestArvArpCd { get; set; }
        public string SchEqpCd { get; set; }
        public string LatestEqpCd { get; set; }
        public string LatestEqpCdType { get; set; }
        public string SchTailNr { get; set; }
        public string LatestTailNr { get; set; }
        public string CnclCd { get; set; }
        public string LocalRemarks { get; set; }
        public string CancelledTime { get; set; }
        public string SvcType { get; set; }
        public string FltManipCode { get; set; }
        public string LegStatus { get; set; }
        public string CarrierCode { get; set; }
        public System.DateTime EstDepDt { get; set; }
        public System.DateTime EstArvDt { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string PreStartStatus { get; set; }
        public string PreEndStatus { get; set; }
        public string GrdReturn { get; set; }
        public string DepGates { get; set; }
    }
}
