//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtpFlightInfo
    {
        public long sequence_Number { get; set; }
        public Nullable<System.DateTime> flight_Date { get; set; }
        public string flight_Number { get; set; }
        public Nullable<System.DateTime> scheduled_Departure_DateTime { get; set; }
        public Nullable<System.DateTime> scheduled_Arrival_DateTime { get; set; }
        public Nullable<System.DateTime> actual_Departure_DateTime { get; set; }
        public Nullable<System.DateTime> actual_Arrival_DateTime { get; set; }
        public Nullable<System.DateTime> publish_Departure_DateTime { get; set; }
        public Nullable<System.DateTime> publish_Arrival_DateTime { get; set; }
        public string actual_Departure_Airport { get; set; }
        public string actual_Arrival_Airport { get; set; }
        public string status { get; set; }
        public string current_Status { get; set; }
        public int Id { get; set; }
    
        public virtual OtpPassengerDetail OtpPassengerDetail { get; set; }
    }
}
