//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class otpGatesdep
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FltDt { get; set; }
        public string FltNr { get; set; }
        public string Dep { get; set; }
        public string Arr { get; set; }
        public string Gat { get; set; }
        public Nullable<System.DateTime> Bstpln { get; set; }
        public Nullable<System.DateTime> Gclpln { get; set; }
    }
}
