//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtpPassengerDetail
    {
        public long flight_Sequence_Number { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> first { get; set; }
        public Nullable<int> business { get; set; }
        public Nullable<int> coach { get; set; }
        public Nullable<int> adult { get; set; }
        public Nullable<int> child { get; set; }
        public Nullable<int> infant { get; set; }
        public string seatConfig { get; set; }
        public string ySeatConfig { get; set; }
        public string jSeatConfig { get; set; }
        public Nullable<int> bookedJ { get; set; }
        public Nullable<int> bookedY { get; set; }
    
        public virtual OtpFlightInfo OtpFlightInfo { get; set; }
    }
}
