//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupDetail
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Zone { get; set; }
        public string FlightDetails { get; set; }
        public Nullable<System.DateTime> FlightDateTime { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Position { get; set; }
        public string Name { get; set; }
        public string StaffNumber { get; set; }
        public Nullable<bool> Is_deleted { get; set; }
        public Nullable<int> Bus_Id { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PickupDateTime { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual CrewDetail CrewDetail { get; set; }
        public virtual TransportGroup TransportGroup { get; set; }
    }
}
