//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PilotCrewDocRejectReason
    {
        public int Id { get; set; }
        public int DocId { get; set; }
        public int ReasonId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> History_Id { get; set; }
    
        public virtual DocumentRejectReason DocumentRejectReason { get; set; }
        public virtual PilotCrewDocument PilotCrewDocument { get; set; }
        public virtual PilotCrewDocumentStatusHistory PilotCrewDocumentStatusHistory { get; set; }
    }
}
