//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PilotDetail
    {
        public string StaffNumber { get; set; }
        public string FullName { get; set; }
        public string Nation { get; set; }
        public string Category { get; set; }
        public string Lang1 { get; set; }
        public string Lang2 { get; set; }
        public string Lang3 { get; set; }
        public string Lang4 { get; set; }
        public string Sex { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PA { get; set; }
    }
}
