//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PilotCrewDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PilotCrewDetail()
        {
            this.Crew_Grooming = new HashSet<Crew_Grooming>();
            this.CrewEffectiveSeniorities = new HashSet<CrewEffectiveSeniority>();
            this.CrewLeaveRequests = new HashSet<CrewLeaveRequest>();
            this.CrewTransportRequests = new HashSet<CrewTransportRequest>();
            this.PilotCrewDocuments = new HashSet<PilotCrewDocument>();
        }
    
        public string StaffNumber { get; set; }
        public string FullName { get; set; }
        public string Nation { get; set; }
        public string Category { get; set; }
        public string Lang1 { get; set; }
        public string Lang2 { get; set; }
        public string Lang3 { get; set; }
        public string Lang4 { get; set; }
        public string Sex { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crew_Grooming> Crew_Grooming { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewEffectiveSeniority> CrewEffectiveSeniorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewLeaveRequest> CrewLeaveRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewTransportRequest> CrewTransportRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PilotCrewDocument> PilotCrewDocuments { get; set; }
    }
}
