//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PilotCrewDocumentStatusHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PilotCrewDocumentStatusHistory()
        {
            this.PilotCrewDocRejectReasons = new HashSet<PilotCrewDocRejectReason>();
        }
    
        public int Id { get; set; }
        public int Document_Id { get; set; }
        public string StaffNumber { get; set; }
        public string Comments { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Change_DT { get; set; }
        public string Attachment_Path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PilotCrewDocRejectReason> PilotCrewDocRejectReasons { get; set; }
        public virtual PilotCrewDocument PilotCrewDocument { get; set; }
    }
}
