//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PilotCrewDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PilotCrewDocument()
        {
            this.CrewDocumentStatusHistories = new HashSet<CrewDocumentStatusHistory>();
            this.PilotCrewDocRejectReasons = new HashSet<PilotCrewDocRejectReason>();
            this.PilotCrewDocumentStatusHistories = new HashSet<PilotCrewDocumentStatusHistory>();
        }
    
        public int Id { get; set; }
        public int Document_Type { get; set; }
        public string StaffNumber { get; set; }
        public string Comments { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Submited_DT { get; set; }
        public string Admin_Reason { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Dt { get; set; }
        public string Attachment_Path { get; set; }
        public string file_name { get; set; }
    
        public virtual CrewDocumentCategory CrewDocumentCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewDocumentStatusHistory> CrewDocumentStatusHistories { get; set; }
        public virtual PilotCrewDetail PilotCrewDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PilotCrewDocRejectReason> PilotCrewDocRejectReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PilotCrewDocumentStatusHistory> PilotCrewDocumentStatusHistories { get; set; }
    }
}
