//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreFlight_TestExlude
    {
        public int id { get; set; }
        public Nullable<int> CrewPosId { get; set; }
        public string Comments { get; set; }
        public string StaffNumber { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<int> FlightId { get; set; }
    
        public virtual OCB_CrewPos OCB_CrewPos { get; set; }
        public virtual OCB_CrewPos OCB_CrewPos1 { get; set; }
        public virtual OCB_Flights OCB_Flights { get; set; }
    }
}
