//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreFlight_Comments
    {
        public int id { get; set; }
        public int CrewTestId { get; set; }
        public string Comments { get; set; }
        public string StaffNumber { get; set; }
        public string DelayTime { get; set; }
    
        public virtual PreFlight_CrewTest PreFlight_CrewTest { get; set; }
    }
}
