//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreFlight_Settings
    {
        public int ID { get; set; }
        public Nullable<int> NumOfMin { get; set; }
        public Nullable<int> NumOfTry { get; set; }
        public string EmailUsername { get; set; }
        public string EmailSendFrom { get; set; }
        public string EmailSendFromPassword { get; set; }
        public string EmailSendTo { get; set; }
        public string EmailSMTP { get; set; }
        public Nullable<bool> ChangeQuestionIfWrong { get; set; }
        public Nullable<int> NumOfQuestions { get; set; }
        public Nullable<int> NumOfCorrect { get; set; }
        public string PassPercentage { get; set; }
    }
}
