//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreFlight_CrewTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreFlight_CrewTest()
        {
            this.PreFlight_Comments = new HashSet<PreFlight_Comments>();
            this.PreFlight_FailedComments = new HashSet<PreFlight_FailedComments>();
            this.PreFlight_TestLog = new HashSet<PreFlight_TestLog>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CrewPosId { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<System.DateTime> TestDateTime { get; set; }
        public Nullable<bool> AllowSecondChance { get; set; }
        public Nullable<bool> DidSecondChance { get; set; }
        public Nullable<bool> IsFaildTest { get; set; }
    
        public virtual OCB_CrewPos OCB_CrewPos { get; set; }
        public virtual OCB_Flights OCB_Flights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFlight_Comments> PreFlight_Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFlight_FailedComments> PreFlight_FailedComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFlight_TestLog> PreFlight_TestLog { get; set; }
    }
}
