//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharePointLog
    {
        public int Id { get; set; }
        public string LogId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string Operation { get; set; }
        public string StaffNumber { get; set; }
        public string SourceURL { get; set; }
        public string FileName { get; set; }
    
        public virtual CrewDetail CrewDetail { get; set; }
    }
}
