//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialMeal
    {
        public int Id { get; set; }
        public string Class { get; set; }
        public string Meal_Type { get; set; }
        public string Passenger_Name { get; set; }
        public string Equipment { get; set; }
        public string Departure { get; set; }
        public string Arrival { get; set; }
        public string Aircraft_Type { get; set; }
        public string FLT_SEQ_NR { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public string guid { get; set; }
        public Nullable<int> FlightId { get; set; }
    
        public virtual OCB_Flights OCB_Flights { get; set; }
    }
}
