//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRecency
    {
        public Nullable<long> SEQNUM { get; set; }
        public string StaffNumber { get; set; }
        public Nullable<System.DateTime> Block_Date { get; set; }
        public string PosCode { get; set; }
        public string FullName { get; set; }
        public string Family { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
    }
}
