//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightMinMaxSetting
    {
        public int id { get; set; }
        public Nullable<decimal> min_weight { get; set; }
        public Nullable<decimal> max_weight { get; set; }
        public Nullable<decimal> height { get; set; }
        public string gender { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> variance_settings_id { get; set; }
    
        public virtual WeightVarianceSetting WeightVarianceSetting { get; set; }
    }
}
