//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBriefingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneArea
    {
        public int Id { get; set; }
        public Nullable<int> Zone_ID { get; set; }
        public string Area { get; set; }
    
        public virtual Zone Zone { get; set; }
    }
}
